# Generated by Django 3.2.25 on 2025-06-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
    ]
