# Generated by Django 3.2.25 on 2025-06-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografía',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('fallecimiento', models.DateField(blank=True, null=True)),
                ('nombre_artístico', models.CharField(max_length=200)),
                ('tipo_de_fotografía', models.CharField(max_length=200)),
                ('características', models.TextField()),
                ('tecnicas', models.TextField()),
                ('exposiciones', models.TextField()),
                ('cantidad_de_fotos', models.IntegerField()),
                ('fotos_destacadas', models.IntegerField()),
                ('nominaciones', models.IntegerField()),
                ('premios', models.CharField(max_length=200)),
                ('opinion_personal', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
