# Generated by Django 3.2.25 on 2025-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_fotografía'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografía',
            name='edad',
            field=models.IntegerField(default=1),
        ),
    ]
