# Generated by Django 3.2.25 on 2025-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_fotografía_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografía',
            name='estilo',
            field=models.CharField(default='por ejemplos, retratos,paisajes,etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='fotografía',
            name='lugar_nacimiento',
            field=models.CharField(default='ejemplo: Buenos Aires, Argentina', max_length=200),
        ),
        migrations.AddField(
            model_name='fotografía',
            name='nacionalidad',
            field=models.CharField(default='ejemplo: Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='fotografía',
            name='ocupación',
            field=models.CharField(default='ejemplo: Fotógrafo, Artista, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='fotografía',
            name='edad',
            field=models.IntegerField(default='ejemplo 30, o edad de fallecimiento'),
        ),
    ]
