# Generated by Django 3.2.25 on 2025-06-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20250622_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografía',
            old_name='tipo_de_fotografía',
            new_name='tipo_de_fotografía_o_movimiento',
        ),
    ]
