# Generated by Django 3.2.25 on 2025-06-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_tipo_de_fotografía_fotografía_tipo_de_fotografía_o_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografía',
            name='cantidad_de_fotos',
        ),
        migrations.RemoveField(
            model_name='fotografía',
            name='fotos_destacadas',
        ),
        migrations.RemoveField(
            model_name='fotografía',
            name='nominaciones',
        ),
        migrations.RemoveField(
            model_name='fotografía',
            name='premios',
        ),
    ]
