# Generated by Django 3.2.25 on 2025-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_fotografía_opinion_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografía',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_publicaciones/'),
        ),
    ]
