# Generated by Django 3.2.25 on 2025-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_fotografía_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografía',
            name='nombre_imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
